module Babeltrace2

  BT_FUNC_STATUS_OVERFLOW_ERROR = -75
  private_constant :BT_FUNC_STATUS_OVERFLOW_ERROR
  BT_FUNC_STATUS_MEMORY_ERROR = -12
  private_constant :BT_FUNC_STATUS_MEMORY_ERROR
  BT_FUNC_STATUS_USER_ERROR = -2
  private_constant :BT_FUNC_STATUS_USER_ERROR
  BT_FUNC_STATUS_ERROR = -1
  private_constant :BT_FUNC_STATUS_ERROR
  BT_FUNC_STATUS_OK = 0
  private_constant :BT_FUNC_STATUS_OK
  BT_FUNC_STATUS_END = 1
  private_constant :BT_FUNC_STATUS_END
  BT_FUNC_STATUS_NOT_FOUND = 2
  private_constant :BT_FUNC_STATUS_NOT_FOUND
  BT_FUNC_STATUS_INTERRUPTED = 4
  private_constant :BT_FUNC_STATUS_INTERRUPTED
  BT_FUNC_STATUS_NO_MATCH = 6
  private_constant :BT_FUNC_STATUS_NO_MATCH
  BT_FUNC_STATUS_AGAIN = 11
  private_constant :BT_FUNC_STATUS_AGAIN
  BT_FUNC_STATUS_UNKNOWN_OBJECT = 42
  private_constant :BT_FUNC_STATUS_UNKNOWN_OBJECT

end
